steps:
  # בניית ודחיפת תמונת Docker ל-Flask
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA', './flask-app']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA']

  # בניית ודחיפת תמונת Docker ל-Node.js
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/node-app:$SHORT_SHA', './node-app']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/node-app:$SHORT_SHA']

  # החלפת תגיות התמונות בקבצי ה-Kubernetes
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i 's|IMAGE_TAG|'"$SHORT_SHA"'|g' k8s/flask-deployment.yaml
        sed -i 's|IMAGE_TAG|'"$SHORT_SHA"'|g' k8s/nodejs-deployment.yaml

  # אימות מול ה-Cluster של GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'my-cluster'          # החלף בשם ה-Cluster שלך
      - '--region'
      - 'us-west2'            # החלף באזור שלך
      - '--project'
      - '$PROJECT_ID'

  # פריסת המשאבים ל-Cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/'

images:
  - 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/node-app:$SHORT_SHA'

options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
