steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    # Example step that references your secrets as environment variables
    entrypoint: 'bash'
    secretEnv: ['DB_USER', 'DB_PASSWORD']
    args:
      - '-c'
      - |
        echo "We won't print the secrets here for security, 
              but they're available in DB_USER and DB_PASSWORD."


  # Clean up unused Docker images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['image', 'prune', '-f']

  # Build and push Docker image for Flask
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA', './flask-app']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA']

  # Build and push Docker image for Flask App 2
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app2:$SHORT_SHA', './flask-app2']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-app2:$SHORT_SHA']

  # Build and push Docker image for Node.js
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/node-app:$SHORT_SHA', './node-app']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/node-app:$SHORT_SHA']

  # Replace PROJECT_ID and IMAGE_TAG in deployment files
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i 's|PROJECT_ID|'"$PROJECT_ID"'|g; s|IMAGE_TAG|'"$SHORT_SHA"'|g' k8s/flask-deployment.yaml
        sed -i 's|PROJECT_ID|'"$PROJECT_ID"'|g; s|IMAGE_TAG|'"$SHORT_SHA"'|g' k8s/nodejs-deployment.yaml
  

  # Deploy resources to the cluster using ADC
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=me-west1'         # Replace with your region
      - 'CLOUDSDK_CONTAINER_CLUSTER=mashcantas'  # Replace with your cluster name
      - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
      - 'CLOUDSDK_CONTAINER_USE_APPLICATION_DEFAULT_CREDENTIALS=true'
secrets:
  secretEnv:
    DB_USER: db-user
    DB_PASSWORD: db-password

images:
  - 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/flask-app2:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/node-app:$SHORT_SHA'

options:
  substitution_option: 'ALLOW_LOOSE' # Allow use of undefined variables
  logging: CLOUD_LOGGING_ONLY
