steps:
  # בניית ודחיפת תמונת Docker ל-Flask
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA', './flask-app']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA']

  # בניית ודחיפת תמונת Docker ל-Node.js
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/node-app:$SHORT_SHA', './node-app']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/node-app:$SHORT_SHA']

  # החלפת PROJECT_ID ו-IMAGE_TAG בקבצי ה-Deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i 's|PROJECT_ID|'"$PROJECT_ID"'|g; s|IMAGE_TAG|'"$SHORT_SHA"'|g' k8s/flask-deployment.yaml
        sed -i 's|PROJECT_ID|'"$PROJECT_ID"'|g; s|IMAGE_TAG|'"$SHORT_SHA"'|g' k8s/nodejs-deployment.yaml

  # שלב לבדיקת תוכן הקבצים לאחר ההחלפה (אופציונלי)
  - name: 'alpine'
    entrypoint: 'cat'
    args:
      - 'k8s/flask-deployment.yaml'
  - name: 'alpine'
    entrypoint: 'cat'
    args:
      - 'k8s/nodejs-deployment.yaml'

  # פריסת המשאבים ל-Cluster באמצעות ADC
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-west2'         # החלף באזור שלך
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'    # החלף בשם ה-Cluster שלך
      - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
      - 'CLOUDSDK_CONTAINER_USE_APPLICATION_DEFAULT_CREDENTIALS=true'

images:
  - 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/node-app:$SHORT_SHA'

options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
