steps:
  # ... שלבי הבנייה והדחיפה

  # החלפת המשתנים בקבצי ה-Deployment באמצעות envsubst
  - name: 'gcr.io/cloud-builders/envsubst'
    args:
      - '-variable'
      - 'PROJECT_ID,IMAGE_TAG'
      - '-o'
      - 'k8s/flask-deployment.yaml'
      - 'k8s/flask-deployment.yaml'
    env:
      - 'PROJECT_ID=${_PROJECT_ID}'
      - 'IMAGE_TAG=${_IMAGE_TAG}'

  - name: 'gcr.io/cloud-builders/envsubst'
    args:
      - '-variable'
      - 'PROJECT_ID,IMAGE_TAG'
      - '-o'
      - 'k8s/nodejs-deployment.yaml'
      - 'k8s/nodejs-deployment.yaml'
    env:
      - 'PROJECT_ID=${_PROJECT_ID}'
      - 'IMAGE_TAG=${_IMAGE_TAG}'

  # פריסת המשאבים ל-Cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-west2'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
      - 'CLOUDSDK_CORE_PROJECT=${_PROJECT_ID}'
      - 'CLOUDSDK_CONTAINER_USE_APPLICATION_DEFAULT_CREDENTIALS=true'

substitutions:
  _PROJECT_ID: $PROJECT_ID
  _IMAGE_TAG: $SHORT_SHA

images:
  - 'gcr.io/${_PROJECT_ID}/flask-app:${_IMAGE_TAG}'
  - 'gcr.io/${_PROJECT_ID}/node-app:${_IMAGE_TAG}'

options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
