apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    networking.gke.io/managed-certificates: "multi-cert"
    networking.gke.io/ingress.class: "gce"  # Specify GCE Ingress
    networking.gke.io/allow-http: "true"   # Disable HTTP
    networking.gke.io/ssl-policy: "MODERN"  # Optional: Define SSL policy
spec:
  tls:
    - hosts:
        - flask.mashcantas.com
  rules:
    - host: flask.mashcantas.com
      http:
        paths:
          - path: /api/flask
            pathType: Prefix
            backend:
              service:
                name: flask-service
                port:
                  number: 5000
