apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flask-cert
  namespace: default
spec:
  secretName: flask-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: flask.mashcantas.com
  dnsNames:
    - flask.mashcantas.com
