apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nodejs-backendconfig
  namespace: default
spec:
  healthCheck:
    type: HTTP
    requestPath: /healthz
    port: 3000
    checkIntervalSec: 30
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 10
