apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: node-cert
  namespace: default
spec:
  secretName: node-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: node.mashcantas.com
  dnsNames:
    - node.mashcantas.com
