apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-ingress
  annotations:                 # (1)
    cert-manager.io/cluster-issuer: "letsencrypt-prod"      # (2)
    nginx.ingress.kubernetes.io/server-snippet: |          # (3)
      if ($scheme = http) {
          return 403;
      }
spec:
  ingressClassName: nginx                                   # (4)
  tls:
    - hosts:
        - node.mashcantas.com                              # (5)
      secretName: node-tls                                  # (6)
  rules:
    - host: node.mashcantas.com
      http:
        paths:
          - path: /api/node
            pathType: Prefix
            backend:
              service:
                name: nodejs-service
                port:
                  number: 3000
          - path: /api/fetch
            pathType: Prefix
            backend:
              service:
                name: nodejs-service
                port:
                  number: 3000
